spring:
  application:
    name: team-knowledge-assistant
  profiles:
    default: local
  jpa:
    open-in-view: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
